<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ml_picking_robot">

  <!-- Same properties as before -->
  <xacro:property name="PI" value="3.14159265359"/>
  <xacro:property name="base_height" value="0.05"/>
  <xacro:property name="base_radius" value="0.15"/>
  <xacro:property name="link_radius" value="0.03"/>
  <xacro:property name="link1_length" value="0.3"/>
  <xacro:property name="link2_length" value="0.25"/>
  <xacro:property name="link3_length" value="0.2"/>

  <!-- Materials -->
  <material name="blue"><color rgba="0.0 0.0 0.8 1.0"/></material>
  <material name="red"><color rgba="0.8 0.0 0.0 1.0"/></material>
  <material name="green"><color rgba="0.0 0.8 0.0 1.0"/></material>
  <material name="grey"><color rgba="0.5 0.5 0.5 1.0"/></material>

  <!-- BASE LINK -->
  <link name="base_link">
    <visual>
      <geometry><cylinder radius="${base_radius}" length="${base_height}"/></geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry><cylinder radius="${base_radius}" length="${base_height}"/></geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <!-- LINK 1 -->
  <joint name="base_joint" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 ${base_height/2 + link_radius}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100" lower="${-PI}" upper="${PI}" velocity="1.0"/>
  </joint>

  <link name="link1">
    <visual>
      <geometry><cylinder radius="${link_radius}" length="${link1_length}"/></geometry>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry><cylinder radius="${link_radius}" length="${link1_length}"/></geometry>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
      <inertia ixx="0.05" ixy="0.0" ixz="0.0" iyy="0.05" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- LINK 2 -->
  <joint name="shoulder_joint" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${link1_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="50" lower="${-PI/2}" upper="${PI/2}" velocity="1.0"/>
  </joint>

  <link name="link2">
    <visual>
      <geometry><cylinder radius="${link_radius * 0.8}" length="${link2_length}"/></geometry>
      <origin xyz="${link2_length/2} 0 0" rpy="0 ${PI/2} 0"/>
      <material name="red"/>
    </visual>
    <collision>
      <geometry><cylinder radius="${link_radius * 0.8}" length="${link2_length}"/></geometry>
      <origin xyz="${link2_length/2} 0 0" rpy="0 ${PI/2} 0"/>
    </collision>
    <inertial>
      <mass value="1.5"/>
      <origin xyz="${link2_length/2} 0 0" rpy="0 ${PI/2} 0"/>
      <inertia ixx="0.02" ixy="0.0" ixz="0.0" iyy="0.02" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- LINK 3 -->
  <joint name="elbow_joint" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="${link2_length} 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="30" lower="${-PI/2}" upper="${PI/2}" velocity="1.0"/>
  </joint>

  <link name="link3">
    <visual>
      <geometry><cylinder radius="${link_radius * 0.6}" length="${link3_length}"/></geometry>
      <origin xyz="${link3_length/2} 0 0" rpy="0 ${PI/2} 0"/>
      <material name="green"/>
    </visual>
    <collision>
      <geometry><cylinder radius="${link_radius * 0.6}" length="${link3_length}"/></geometry>
      <origin xyz="${link3_length/2} 0 0" rpy="0 ${PI/2} 0"/>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="${link3_length/2} 0 0" rpy="0 ${PI/2} 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.005"/>
    </inertial>
  </link>

  <!-- GRIPPER BASE -->
  <joint name="wrist_joint" type="revolute">
    <parent link="link3"/>
    <child link="gripper_base"/>
    <origin xyz="${link3_length} 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="10" lower="${-PI}" upper="${PI}" velocity="2.0"/>
  </joint>

  <link name="gripper_base">
    <visual>
      <geometry><box size="0.08 0.06 0.04"/></geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry><box size="0.08 0.06 0.04"/></geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <!-- GRIPPER FINGERS -->
  <joint name="left_finger_joint" type="prismatic">
    <parent link="gripper_base"/>
    <child link="left_finger"/>
    <origin xyz="0.04 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="20" lower="0.0" upper="0.04" velocity="0.1"/>
  </joint>

  <link name="left_finger">
    <visual>
      <geometry><box size="0.02 0.01 0.08"/></geometry>
      <origin xyz="0 0 -0.04" rpy="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry><box size="0.02 0.01 0.08"/></geometry>
      <origin xyz="0 0 -0.04" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 -0.04" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="right_finger_joint" type="prismatic">
    <parent link="gripper_base"/>
    <child link="right_finger"/>
    <origin xyz="0.04 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="20" lower="-0.04" upper="0.0" velocity="0.1"/>
    <mimic joint="left_finger_joint" multiplier="-1"/>
  </joint>

  <link name="right_finger">
    <visual>
      <geometry><box size="0.02 0.01 0.08"/></geometry>
      <origin xyz="0 0 -0.04" rpy="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry><box size="0.02 0.01 0.08"/></geometry>
      <origin xyz="0 0 -0.04" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 -0.04" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <!-- CAMERA -->
  <joint name="camera_joint" type="fixed">
    <parent link="gripper_base"/>
    <child link="camera_link"/>
    <origin xyz="0.05 0 0.02" rpy="0 0 0"/>
  </joint>

  <link name="camera_link">
    <visual>
      <geometry><box size="0.02 0.04 0.02"/></geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry><box size="0.02 0.04 0.02"/></geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <!-- GAZEBO PLUGINS -->
  <gazebo reference="camera_link">
    <sensor type="camera" name="camera1">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <ros><namespace>/camera</namespace></ros>
        <camera_name>camera</camera_name>
        <frame_name>camera_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Joint state publisher -->
  <gazebo>
    <plugin name="gazebo_ros_joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <ros><namespace>/</namespace><remapping>~/out:=joint_states</remapping></ros>
      <update_rate>50</update_rate>
      <joint_name>base_joint</joint_name>
      <joint_name>shoulder_joint</joint_name>
      <joint_name>elbow_joint</joint_name>
      <joint_name>wrist_joint</joint_name>
      <joint_name>left_finger_joint</joint_name>
      <joint_name>right_finger_joint</joint_name>
    </plugin>
  </gazebo>

</robot>
